pyproject.toml

The version number is inferred from decomon.__version__ defined in decomon/__init__.py.
The dependencies are a bit relaxed:
- the spec with ^ is specific to poetry
- some dependencies where included by other ones

Update pyproject.toml to switch from poetry to setuptools

---

decomon/__init__.py
pyproject.toml

To be consistent, we define `decomon.__version__` by looking at metadata of installed package. If not installed,  `__version__ `remains undefined. We need importlib-metadata for that which is by default on python 3.8 but must be installed for previous versions.
cf https://github.com/pypa/setuptools_scm#retrieving-package-version-at-runtime
The version will be inferred from distance to tags of the form "v{x}.{y}.{z}" or "{x}.{y}.{z}" where {x}, {y}, and {z} are numbers.

Infer version number from git tags thanks to setuptools_scm

---

decomon/numpy/milp/activation.py
pyproject.toml

We want the library to work without ortools as long as we do not use the functions using it.

Make ortools dependency optional

---

.github/workflows/python-tests.yml

At each push, the doc
- is generated
- is uploaded as an artifact
- is published if on default branch (main) via github pages (available at https://airbus.github.io/decomon/main)
Notes:
- One can have a look to the generated doc, even when not on the default branch by:
- Downloading it (click on the appropriate "doc" link in the available artifacts link in the github action summary
- Extracting it to a folder: `mkdir tmp; mv ~/Downloads/doc.zip tmp; cd tmp; unzip doc.zip`
- Serving it with an html server: `python -m http.server`
- To allow the github pages publication, it is necessary to activate it via repository settings, and to choose gh-pages branch as github-pages source

Generate and deploy dev doc via github actions

---

.github/workflows/build-doc.yml
.github/workflows/python-publish.yml
.pre-commit-config.yaml
docs/generate_nb_index.py
docs/source/contribute.md
tutorials/tutorial1_sinus-interactive.ipynb
tutorials/tutorial2_noise_sensor.ipynb
tutorials/tutorial3_adversarial_attack.ipynb
tutorials/tutorial4_adversarial_brightness.ipynb

- Add links in doc for opening notebooks in colab
- Add a cell in notebooks installing decomon (from main branch) in case they are run from colab
- When deploying a release (tag "vx.y.z") we modify the notebooks to install decomon from pip with the appropriate version number and push them to a dedicated tag ("tutorials-vx.y.z"), and the links in the release doc will point to them

Add tutorials on colab

---

.github/workflows/python-tests.yml
tox.ini

- Add coverage only for one tox env (py39-linux) to avoid duplicate report
- Upload the coverage report as an artifact

Add coverage in test suite

---

index.html

- .nojekyll: tells github pages that this is not a Jekyll website
- index:html: the documentation versions are available under subdirectories "main/" for default branch, and "x.y.z" for release "x.y.z". So we need an index file at root of https://airbus.github.io/decomon redirecting towards a valid documentation. Here we chose the developper documentation corresponding to code available in "main" branch

Add index.html and .nojekyll at github pages root

---

src/decomon/layers/activations.py
src/decomon/layers/utils.py
src/decomon/metrics/loss.py
src/decomon/models/convert.py
src/decomon/utils.py

When casting to a float, use rather dtype of current tensor instead of K.floatx() which sometimes does not reference the proper version of float (16, 32, or 64).
At some other places, we needed also to cast to the appropriate dtype and this PR fix them.

Use x.dtype instead of K.floatx() in K.cast()

---

.pre-commit-config.yaml

Previous version would not install properly with last version of pre-commit.

Bump isort pre-commit hook

---

.github/workflows/deploy-doc.yml
.github/workflows/python-publish.yml
.github/workflows/python-tests.yml
binder/environment.yml
docs/generate_nb_index.py
scripts/trigger_binder.sh

- Add the environment settings in binder/ directory
- Add the appropriate links to tutorials page of the doc to launch the notebooks
- Update the binder environment when publishing a release to use the decomon library published on PyPi (using the same tag "tutorials_vx.y.z" already created for colab)
- Trigger a build of binder environment at each release and each push on main branch (e.g. when merging PRs) to avoid long waiting time for users following the binder links

Add a binder environment to launch notebooks on binderhub

---

README.md

It avoids redundancy and thus reduce the risk for potential errors in the README as it was the case in the toy example presented in README.

Make README point to online documentation

---

README.md
docs/source/conf.py
docs/source/contribute.md
docs/source/getting_started.md
docs/source/index.md
tutorials/tutorial3_adversarial_attack.ipynb
tutorials/tutorial4_adversarial_brightness.ipynb

Sometimes "DecoMon" and sometimes "decomon" were used. The convention is now to always use lowercase for the library name.

Unify decomon syntax throughout the project

---

src/decomon/backward_layers/backward_layers.py
src/decomon/backward_layers/backward_maxpooling.py
src/decomon/backward_layers/backward_merge.py
src/decomon/backward_layers/core.py
src/decomon/backward_layers/crown.py
src/decomon/backward_layers/deel_lip.py
src/decomon/layers/activations.py
src/decomon/layers/core.py
src/decomon/layers/decomon_layers.py
src/decomon/layers/deel_lip.py
src/decomon/layers/maxpooling.py
src/decomon/metrics/loss.py
src/decomon/metrics/metric.py
src/decomon/models/models.py
tests/test_backward_layers_get_config.py
tests/test_layers_get_config.py
tests/test_metrics_get_config.py
tutorials/Advanced/tensorboard-and-decomon.ipynb

- define get_config() in layers/models specific to Decomon
- define BackwardLayer as a child of keras.layers.Wrapper in order to get the proper get_config() with the referenced layer
- fix the use of relu in DecomonActivation to get the proper get_config (and use the proper activation function by the same way)
- add the related unit tests
- add a notebook (in an "advanced" subsection) demonstrating the visualization with tensorboard

Enable visualization of a decomon model graph with tensorboard

---

src/decomon/backward_layers/activations.py
src/decomon/backward_layers/backward_layers.py
src/decomon/backward_layers/backward_maxpooling.py
src/decomon/backward_layers/backward_merge.py
src/decomon/backward_layers/core.py
src/decomon/backward_layers/deel_lip.py
src/decomon/models/backward_cloning.py
src/decomon/models/convert.py
tests/conftest.py
tests/test_backward_activation.py
tests/test_backward_conv.py
tests/test_backward_dense.py
tests/test_backward_layers.py
tests/test_backward_native_layers.py

This attribute was forced to `False` in `convert_backward` so we remove it by assuming it `False`.

Remove `previous` attribute from backward layers

---

src/decomon/backward_layers/backward_layers.py
src/decomon/backward_layers/deel_lip.py
src/decomon/backward_layers/utils.py
src/decomon/layers/activations.py
src/decomon/layers/core.py
src/decomon/layers/decomon_layers.py
src/decomon/layers/decomon_merge_layers.py
src/decomon/layers/utils.py
src/decomon/metrics/loss.py
src/decomon/metrics/metric.py
src/decomon/models/backward_cloning.py
src/decomon/models/convert.py
src/decomon/models/forward_cloning.py
src/decomon/models/models.py
src/decomon/models/utils.py
src/decomon/utils.py
src/decomon/wrapper.py
tests/lirpa_comparison/test_comparison_lirpa.py
tests/test_backward_dense.py
tests/test_clone.py
tests/test_clone_backward.py
tests/test_clone_forward.py
tests/test_dense_layer.py
tests/test_wrapper.py

For more consistency, we replace "forward" term by "affine" when it concerns the type of bounds propagated.
We let "forward" when it is about the direction of propagation.
Still to be consistent, we use "ibp" in lower case everywhere (it was sometimes in upper case).
We also fix the use of clone in wrapper.py on the way:
The arguments ibp and affine/forward or mode were passed but not used by clone(), we replace them by "final_ibp" and "final_affine".

Use "affine" instead of "forward" in code for bounds type

---

src/decomon/metrics/loss.py
src/decomon/models/convert.py
src/decomon/models/models.py

The goal is to stay consistent with Keras models which have "inputs" and "ouputs" as main arguments (when defined as functional models), instead of "input" and "output".

Rename DecomonModel main args "inputs" and "outputs"

---

src/decomon/layers/decomon_layers.py
src/decomon/wrapper.py
tests/conftest.py
tests/lirpa_comparison/test_comparison_lirpa.py
tests/test_activation.py
tests/test_backward_activation.py
tests/test_backward_dense.py
tests/test_backward_layers.py
tests/test_clone.py
tests/test_decomon_activation_layer.py
tests/test_wrapper.py

- add a fixture slope in conftest with all possible values that slope can take
- test wrapper: compare call on a preconverted model with slope to a a direct call on a keras model with a given slope arg
- test clone: check that converted layers get the proper slope attribute
- test layers with activation: check that modifying slope modifies result
- test activation functions (only relu for now): check affine bounds found for each slope

Add tests for slope argument

---

src/decomon/models/backward_cloning.py
src/decomon/models/convert.py
src/decomon/models/forward_cloning.py
src/decomon/models/utils.py
tests/test_conv.py

`clone()` function already initialize input_tensors so we can assume that
`input_tensors` is not None` in `convert_forward` and `convert_backward`.
We replace the implementation of `get_input_tensors() `by the one used in
`clone()` and call it within it.
We remove not anymore used `check_input_tensors_sequential()`

Remove duplicate code initializing input_tensors for convert/clone

---

src/decomon/backward_layers/__init__.py
src/decomon/backward_layers/backward_layers.py
src/decomon/backward_layers/convert.py
src/decomon/backward_layers/deel_lip.py
src/decomon/layers/convert.py
src/decomon/layers/core.py
src/decomon/layers/decomon_layers.py
src/decomon/layers/decomon_merge_layers.py
src/decomon/layers/utils.py
src/decomon/metrics/loss.py
src/decomon/models/backward_cloning.py
src/decomon/models/convert.py
src/decomon/models/forward_cloning.py
src/decomon/models/utils.py
tests/test_backward_conv.py
tests/test_backward_dense.py
tests/test_backward_layers.py
tests/test_backward_native_layers.py
tests/test_conv.py
tests/test_decomon_activation_layer.py
tests/test_dense_layer.py
tests/test_merge.py
tests/test_reshape.py
tests/test_to_decomon.py

- put them in dedicated modules decomon.layers.convert and decomon.backward_layers.convert
- share common code between to_decomon() and to_decomon_merge() => single public function to_decomon()
- Instead of globals() use a mapping constructed from vars() applied to relevant module. It avoids explicitely import each Decomon-/Backward-Layer and make the module imports be used so that it is obvious even for IDE that such imports are not to be removed.
- Remove try...except: pass (relic of a past debugging)
- Add a utility functions to check wether a layer is a merge layer and wether a model contains a merge layer

Refactor to_decomon(), to_decomon_merge(), and to_backward()

---

tests/test_activation.py
tests/test_backward_conv.py
tests/test_backward_layers.py
tests/test_backward_native_layers.py
tests/test_clone.py
tests/test_conv.py
tests/test_utils_pooling.py
tests/test_wrapper.py

We were using `return` statement but this is cleaner and clearer as it allows to state the reason and it appears as skipped in pytest report.

Use `pytest.skip` when skipping a test because some condition is not met

---

src/decomon/backward_layers/backward_layers.py
src/decomon/backward_layers/utils.py
src/decomon/layers/convert.py
src/decomon/layers/core.py
src/decomon/layers/decomon_layers.py
src/decomon/layers/utils.py
src/decomon/metrics/loss.py
src/decomon/models/models.py
src/decomon/models/utils.py
src/decomon/utils.py
src/decomon/wrapper.py

- put Option enumeration besides ConvexDomainType enumeration
- when testing convex_domain["name"], first convert it to ConvexDomainType
- when testing convex_domain["option"], first convert it to Option
This PR fix issues in some notebooks which were defining convex domain type by a string. This will be now ok as we convert on-the-fly when checking this convex domain type.

Fix convex_domain use by converting fields to proper enumeration type

---

src/decomon/layers/core.py
src/decomon/layers/decomon_layers.py
src/decomon/layers/decomon_merge_layers.py
src/decomon/layers/decomon_reshape.py
src/decomon/layers/deel_lip.py
src/decomon/layers/maxpooling.py
src/decomon/metrics/loss.py
tests/test_backward_layers_get_config.py
tests/test_layers_get_config.py

- It is the last tensor which has always the proper shape for underlying original Keras layer in inputs for decomon layers => thus in general, we should call the original keras layer's build() on input_shape[-1]
- For merging layers we introduce a base layer DecomonMerge to harmonize build() and also compute_output_shape(). We need to derive first from DecomonMerge to be sure to pass through the proper build().   
- We implement a default version of build in DecomonLayer.
- To avoid issues to know which build is called when using super().call(), we introduce a new attribute `original_keras_layer_class`, to be overriden in each subclass of  DecomonLayer. This is the keras layer from which this decomon layer is the decomon equivalent.
- We use this new attribute to get also a default …

Fix issues in decomon layers build()

---

tutorials/tutorial1_sinus-interactive.ipynb
tutorials/tutorial2_noise_sensor.ipynb

- Add a missing paper reference in tuto 2;
- Correct the type of bounds available depending of chosen method for `clone()`.

Fix minor issues in notebooks texts

---

src/decomon/layers/decomon_layers.py
tests/test_decomon_reset_layer.py

In that case `self.beta` (resp. `self.gamma`) are `None`, and thus `beta_` (resp. `gamma_`) must be 0 (resp 1).
We reactivate the test that was xfailed waiting for this correction.

Implement DecomonBatchNormalization.call with center or scale = False

---

tests/conftest.py
tests/test_activation.py
tests/test_backward_activation.py
tests/test_backward_conv.py
tests/test_backward_dense.py
tests/test_backward_layers.py
tests/test_backward_layers_get_config.py
tests/test_backward_native_layers.py
tests/test_backward_utils.py
tests/test_clone.py
tests/test_clone_backward.py
tests/test_clone_forward.py
tests/test_conv.py
tests/test_decomon_activation_layer.py
tests/test_decomon_reset_layer.py
tests/test_dense_layer.py
tests/test_merge.py
tests/test_metric.py
tests/test_pooling.py
tests/test_reshape.py
tests/test_utils.py
tests/test_utils_pooling.py
tests/test_wrapper.py

Fixes:
- Use appropriate inputs when testing decomon models (the are different from the one for decomon layers)
Clarification & refactoring:
- Add fixtures to avoid code duplication and simplify the tests
- keras/decomon model creation
- setting floatx and epsilon back and forth (using teardown feature)
- extraction of appropriate inputs from fulll inputs according to mode for decomon layers, keras layers, decomon models
- creation of full outputs from the outputs of decomon layers depending on modes
- assert based using directly ouputs from layers/models and full inputs (without having to decompose everything)
- with auto-reconstruction of backward bounds when testing backward layers

Improve and simplify tests

---

src/decomon/layers/convert.py
tests/conftest.py
tests/test_clone.py

Test clone and resulting bounds on
- 1d toy models
- cnn model (with a first reshape layer to feed it with flatten multid inputs)
- deel-lip model (with layers having an export_vanilla method only)

Add tests for clone on more toy models

---

src/decomon/backward_layers/backward_layers.py

The dimension should be deduced from last input tensor instead of first one so that it works for all modes.

Fix BackwardBatchNormalization.call()

---

src/decomon/layers/utils_pooling.py

- compute upper linear hull of pooling by compute the linear relaxations over a pre-defined set of corners
- when the input domain collapsed on some dimensions, the method was raising an error at running time
- we artificially increase the input domain of the pooling layer on *collapsed* dimensions which do not affect the soundness

Pooling collapse

---

.github/workflows/deploy-doc.yml

gke is not part of the mybinder federation anymore: https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f

Stop triggering binder build on gke

---

src/decomon/backward_layers/activations.py
src/decomon/backward_layers/backward_maxpooling.py
src/decomon/backward_layers/utils.py
src/decomon/core.py
src/decomon/layers/__init__.py
src/decomon/layers/activations.py
src/decomon/layers/convert.py
src/decomon/layers/decomon_layers.py
src/decomon/layers/maxpooling.py
src/decomon/layers/utils.py
src/decomon/layers/utils_pooling.py
src/decomon/metrics/loss.py
src/decomon/metrics/metric.py
src/decomon/models/backward_cloning.py
src/decomon/models/crown.py
src/decomon/models/utils.py
src/decomon/utils.py
tests/test_utils.py

- We replace get_upper/get_lower functions by call to perturbation_domain.get_upper/get_lower
- This allowed to detect places where the perturbation domain was not specified
- We unify definition of x input shape by using the new method instead of having tests on perturbation domain class

Add methods get_lower/get_upper/get_x_input_shape to PerturbationDomain

---

.github/workflows/python-tests.yml
tox.ini

This is a temporary patch to avoid having tests much too long (>5hours!)
This is related to this issue: https://github.com/keras-team/keras/issues/18301

Force using tf<2.13 in github actions

---

tox.ini

Surprisingly, having the section [testenv:py39-linux-nodeellip] after the more generic section
[testenv:py{39,311}-{linux,macos,win}-nodeellip] skip the more specific section definition.
So the coverage was missed. This can be corrected by putting [testenv:py39-linux-nodeellip] before [testenv:py{39,311}-{linux,macos,win}-nodeellip] but this not intuitive.
We choose here to do everything in the main section [testenv] by making full use of generative names and factor conditions.
In particular, to have a command be used if a given factor is absent, by using an exclamation mark:
!nodeellip: ...

Update and simplify tox config file to ensure test coverage

---

.pre-commit-config.yaml

Sometimes isort can set 3rd-party libaries as 1st-party ones if a random directory with the library name in the project arborescence (on the repository or even locally). And thus make `pre-commit` change wrongly a file.
To avoid this we specify to isort where the source directory for our library is.

Robustify isort linter

---

.github/workflows/build-doc.yml
binder/environment.yml
binder/postBuild
docs/requirements.txt
pyproject.toml
src/decomon/__init__.py
tests/test_keras3.py
tox.ini
tutorials/tutorial1_sinus-interactive.ipynb
tutorials/tutorial2_noise_sensor.ipynb
tutorials/tutorial3_adversarial_attack.ipynb
tutorials/tutorial4_certified_over_estimation.ipynb
tutorials/z_Advanced/tensorboard-and-decomon.ipynb

Keras 3.0 has officially been released: https://keras.io/keras_3/
- We need to update to tensorflow 2.15 compatible with keras 3 (see https://keras.io/getting_started/)
- We still need to reinstall keras 3 after tensorflow 2.15 which install keras 2.15. This will not be necessary starting from tensorflow 2.16.
- We add a check at decomon import and raise an error if keras version is not 3.
- In decomon dependencies, we remove tensorflow as it will now depends on the backend chosen by the user (tensorflow, jax, or pytorch)

Install official release keras 3.0 instead of keras-nightly

---

src/decomon/keras_utils.py
src/decomon/layers/utils_pooling.py
src/decomon/metrics/loss.py
src/decomon/models/backward_cloning.py
src/decomon/models/models.py
src/decomon/models/utils.py
tests/conftest.py
tests/test_activation.py
tests/test_backward_conv.py
tests/test_backward_layers.py
tests/test_backward_native_layers.py
tests/test_clone.py
tests/test_conv.py
tests/test_decomon_reset_layer.py
tests/test_models_utils.py
tests/test_preprocess_keras_model.py
tests/test_utils_conv.py
tests/test_utils_pooling.py
tutorials/tutorial4_certified_over_estimation.ipynb

We still had some code specific to tensorflow that we should make more agnostic now that we are using keras 3 which can work on several backends:
- unconditionned `tensorflow` imports in modules -> removed
- `.numpy()` -> `keras.ops.convert_to_numpy()`
-` tf.linalg.solve()` -> create a `LinalgSolve` keras operation which internally will check the backend to use proper code

Get rid of last tensorflow backend specificities

---

tests/test_backward_conv.py
tests/test_utils_conv.py

The tested data_format was not injected into the tested layer. Thus we were always having layers assuming data_format=channels_last.
NB: this cannot be seen without a gpu for now, because the tests with channels_firt are skipped. 
But we could run the tests on torch which allows channels first even in CPU mode. (This is actually the pytorch preferred data format.)

Fix test_utils_conv.py and test_backward_conv.py

---

src/decomon/backward_layers/backward_layers.py
tests/test_backward_conv.py
tests/test_backward_layers.py
tests/test_backward_native_layers.py
tests/test_conv.py
tests/test_utils_conv.py

- unskip tests with `data_format == "channels_first"` with pytorch (implemented even on CPU as it is the default behaviour)
- xfail `get_toeplitz` tests for data_format == "channels_first" as it is bugged in this case
- fix bias shape in `BackwardConv2d.get_affine_components()`

Test data_format="channels_first" with pytorch

---

src/decomon/backward_layers/backward_layers.py
src/decomon/backward_layers/core.py
tests/conftest.py
tests/test_backward_compute_output_shape.py
tests/test_backward_layer_wo_merge.py
tests/test_backward_layers.py
tests/test_backward_native_layers.py
tests/test_decomon_compute_output_shape.py
tox.ini

- Add a generic compute_output_shape() to allow simple call when dealing with symbolic tensors
- Add a test for compute_output_shape() with backward layers
- Add a test on backward layers outputs without having to merge them with previous backward bounds
- Fix BackwardBatchNormalization
- Fix BackwardDense in case of image-like inputs
- Use pytest-cases to simplify the parametrization of backward layers test
More about testing directly backward layers:
The backward layers are supposed to output lower and upper affine bounds of the action of the original keras layer on the **flatten** keras inputs (knowing some prebounds on the inputs).
So we can check that
w_l_out * flatten_keras_input + b_l_out <= flatten_keras_output
w_u_out * flatten_keras_input + b_u_out >= flatten_keras_output …

Fix backward layers
